# Generated by Django 5.2.8 on 2025-11-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(blank=True, max_length=13)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_id', models.CharField(max_length=20, unique=True)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('warga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.warga')),
            ],
        ),
    ]
