# Generated by Django 5.2.8 on 2025-11-16 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='nomor_id',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='warga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='warga.warga'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='warga',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
