# Generated by Django 5.2.8 on 2025-11-12 09:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_alter_warga_options_alter_warga_alamat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='deskripsi',
            new_name='isi_pengaduan',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='tanggal_lapor',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='pelapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.warga'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warga',
            name='tanggal_registrasi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
