# Generated by Django 5.2.8 on 2025-11-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_remove_pengaduan_nomor_id_pengaduan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('BARU', 'Baru'), ('DIPROSES', 'Diproses'), ('SELESAI', 'Selesai')], default='BARU', max_length=20),
        ),
    ]
