# Generated by Django 5.2.8 on 2025-11-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_rename_deskripsi_pengaduan_isi_pengaduan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20),
        ),
    ]
