# Generated by Django 5.2.8 on 2025-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0004_pengaduan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='pelapor',
            new_name='warga',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='tanggal_registrasi',
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='tanggal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
