# Generated by Django 5.2.8 on 2025-11-14 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0005_rename_pelapor_pengaduan_warga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='isi_pengaduan',
            new_name='deskripsi',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
